name: Deploy HTML Site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Debug SSH Key (Optional)
        run: |
          ls -l ~/.ssh
          head -n 2 ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} "echo '✅ SSH is working'"

      - name: Copy Files to EC2 (Temporary Directory)
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} "mkdir -p ~/deploy-temp"
          scp -i ~/.ssh/id_rsa -r * ubuntu@${{ secrets.EC2_HOST }}:~/deploy-temp/

      - name: Move Files to /var/www/html (With sudo)
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} "sudo mv ~/deploy-temp/* /var/www/html/"
