name: Deploy HTML Site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Debug SSH Key (Optional)
        run: |
          ls -l ~/.ssh
          cat ~/.ssh/id_rsa | head -n 2
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} "echo '✅ SSH is working'"

      - name: Deploy Files to EC2
        run: |
          scp -r * ubuntu@${{ secrets.EC2_HOST }}:/var/www/html/
